spring:
  application:
    name: MvcModule2

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource :
    url: jdbc:h2:file:/Users/avish/Downloads/H2
    username: avishDB
    password: Avish123

  jpa:
    hibernate:
      ddl-auto: update

